.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. sthcoin_qt test_sthcoin_qt
clean: FORCE
	$(MAKE) -C .. sthcoin_qt_clean test_sthcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_sthcoin_qt_check
sthcoin-qt sthcoin-qt.exe: FORCE
	 $(MAKE) -C .. sthcoin_qt
